all: main einmaleins dual methods arrayTools

main: main.c
	gcc -o main main.c

einmaleins.c: einmaleins.c
	gcc -o einmaleins.c	


dual.c: dual.c
	gcc -o dual.c	

methods.c: methods.c
	gcc -o methods.c

arrayTools.c: arrayTools.c
	gcc -o arrayTools.c	
